/*
 * This source file was generated by the Gradle 'init' task
 */
// package org.example;

// import org.junit.Test;
// import org.lox.Lox;

// import static org.junit.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         Lox classUnderTest = new Lox();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
