/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lox;

public class Lox {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Lox().getGreeting());
    }
}
